Import and Load data

In [49]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,  root_mean_squared_error

In [36]:
#path of dataset
df = pd.read_csv("C:\\Users\\Sepehr\\Downloads\\vehicles.csv")
df.head()

              DateTime  Vehicles
0  2015-11-01 00:00:00        15
1  2015-11-01 01:00:00        13
2  2015-11-01 02:00:00        10
3  2015-11-01 03:00:00         7
4  2015-11-01 04:00:00         9

In [37]:
def get_day(dt):
	return dt.day
def get_weekday(dt):
	return dt.weekday()
def get_hour(dt):
	return dt.hour
def get_year(dt):
	return dt.year
def get_month(dt):
	return dt.month
def get_dayofyear(dt):
	return dt.dayofyear
def get_weekofyear(dt):
	return dt.weekofyear

df['DateTime'] = df['DateTime'].map(pd.to_datetime)
df['date'] = df['DateTime'].map(get_day)
df['weekday'] = df['DateTime'].map(get_weekday)
df['hour'] = df['DateTime'].map(get_hour)
df['month'] = df['DateTime'].map(get_month)
df['year'] = df['DateTime'].map(get_year)
df['dayofyear'] = df['DateTime'].map(get_dayofyear)
df['weekofyear'] = df['DateTime'].map(get_weekofyear)

df.head()

,DateTime,Vehicles,date,weekday,hour,month,year,dayofyear,weekofyear
0,2015-11-01 00:00:00,15,1,6,0,11,2015,305,44
1,2015-11-01 01:00:00,13,1,6,1,11,2015,305,44
2,2015-11-01 02:00:00,10,1,6,2,11,2015,305,44
3,2015-11-01 03:00:00,7,1,6,3,11,2015,305,44
4,2015-11-01 04:00:00,9,1,6,4,11,2015,305,44

In [38]:
shuffled = df.sample(frac=1, random_state=42)
print(shuffled)

                 DateTime  Vehicles  date  weekday  hour  month  year  \
24632 2016-12-23 08:00:00         9    23        4     8     12  2016
36428 2016-08-28 20:00:00        97    28        6    20      8  2016
42150 2017-04-24 06:00:00        13    24        0     6      4  2017
23885 2016-11-22 05:00:00        11    22        1     5     11  2016
2174  2016-01-30 14:00:00        24    30        5    14      1  2016
...                   ...       ...   ...      ...   ...    ...   ...
11284 2017-02-13 04:00:00        37    13        0     4      2  2017
44732 2017-02-09 20:00:00         8     9        3    20      2  2017
38158 2016-11-08 22:00:00        10     8        1    22     11  2016
860   2015-12-06 20:00:00        21     6        6    20     12  2015
15795 2015-12-21 03:00:00         5    21        0     3     12  2015

       dayofyear  weekofyear
24632        358          51
36428        241          34
42150        114          17
23885        327          47
2174          30           4
...          ...         ...
11284         44           7
44732         40           6
38158        313          45
860          340          49
15795        355          52

[48120 rows x 9 columns]

In [39]:
print(df["weekofyear"].unique())
print(df["date"].unique())
print(df["weekday"].unique())

[44 45 46 47 48 49 50 51 52 53  1  2  3  4  5  6  7  8  9 10 11 12 13 14
 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31]
[6 0 1 2 3 4 5]

In [40]:
df.columns

Index(['DateTime', 'Vehicles', 'date', 'weekday', 'hour', 'month', 'year',
       'dayofyear', 'weekofyear'],
      dtype='object')

In [41]:
# for remove col we use axis 1
df = df.drop(["DateTime"], axis=1)
X = df.drop(["Vehicles"], axis=1)
y = df['Vehicles']
print(X.head())
y.head()

   date  weekday  hour  month  year  dayofyear  weekofyear
0     1        6     0     11  2015        305          44
1     1        6     1     11  2015        305          44
2     1        6     2     11  2015        305          44
3     1        6     3     11  2015        305          44
4     1        6     4     11  2015        305          44

0    15
1    13
2    10
3     7
4     9
Name: Vehicles, dtype: int64

In [43]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

Model session

In [44]:
model = RandomForestRegressor(n_estimators=300, min_samples_leaf=2, max_depth=8)

model.fit(X_train, y_train)

RandomForestRegressor(max_depth=8, min_samples_leaf=2, n_estimators=300)

Prediction

In [46]:
print(len(y_test))
print(len(X_test))

9624
9624

In [50]:
print("Sample",model.predict([[11,6,0,1,2015,11,2]]))
pred = model.predict(X_test)
print("test data mse:",root_mean_squared_error(y_test, pred))
print("test data mae:",mean_absolute_error(y_test, pred))

c:\Users\Sepehr\miniconda3\envs\ml_env\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

Sample [9.03265875]
test data mse: 18.45035712366381
test data mae: 14.424146267797996